sudo: false
language: java
services:
  - postgresql
script: mvn -T 2C verify
jdk:
#  - oraclejdk8
  - openjdk11
before_script:
  - createuser -U postgres -d -S -R maxcom
  - createuser -U postgres -D -S -R linuxweb
  - createuser -U postgres -D -S -R jamwiki
  - createdb -U maxcom lor
  - psql -f sql/demo.db -U maxcom lor
  - psql -c 'create extension hstore;' -U postgres lor
  - psql -c 'create extension fuzzystrmatch;' -U postgres lor
  - unset GEM_PATH
before_install:
  - unset GEM_PATH
install: mvn -B verify -DskipTests=true -Dmaven.javadoc.skip=true 

git:
  depth: 1
cache:
  directories:
  - $HOME/.m2
