name: Integration Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.8.4-openjdk-11
    services:
      postgres:
        image: postgres:10
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2
      - name: Initialize database	
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
          createuser -h postgres -U postgres -d -S -R maxcom
          createuser -h localhost -U postgres -D -S -R linuxweb
          createuser -h localhost -U postgres -D -S -R jamwiki
          createdb -h localhost -U maxcom lor
          psql -h localhost -c 'create extension hstore;' -U postgres lor
          psql -h localhost -c 'create extension fuzzystrmatch;' -U postgres lor
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build 
        run: mvn --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true package
      - name: Test
        run: mvn --batch-mode test
